# Generated by Django 3.2.4 on 2021-06-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='video/%y')),
                ('demo', models.BooleanField(default=False)),
                ('cat', models.CharField(max_length=300)),
            ],
        ),
    ]
